export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const CREATE_ABC_SORTED_LIST = 'CREATE_ABC_SORTED_LIST';
export const CREATE_MONTH_SORTED_LIST = 'CREATE_MONTH_SORTED_LIST';
export const EMPLOYEES_ERROR = 'EMPLOYEES_ERROR ';
export const CLEAR_EMPLOYEES = 'CLEAR_EMPLOYEES';

export const SET_SHOWBIRTHDAY = 'SET_SHOWBIRTHDAY';
export const CREATE_SHOWBIRTHDAY_LIST = ' CREATE_SHOWBIRTHDAY_LIST';
