export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const EMPLOYEES_ERROR = 'EMPLOYEES_ERROR ';
export const CLEAR_EMPLOYEES = 'CLEAR_EMPLOYEES';

export const CREATE_SORTEDLIST = 'CREATE_SORTEDLIST';
export const CREATE_SORTED_BY_MONTH = 'CREATE_SORTED_BY_MONTH';
export const SET_SHOWBIRTHDAY = 'SET_SHOWBIRTHDAY';
